   export const listProduct =[
        {   _id: "123a",
            name: "Avena molida",
            image: "avena-molida-quaker-x-350-grs.jpg",
            price: 1000,
            description: "avena-lodida-quaker",
        },
        {   _id: "123b",
            name: "Cafe tradicion",
            image: "cafe-tradicion-nescafe-x-170-grs.jpg",
            price: 1000,
            description: "cafe-tradicion-nescafe",
        },
        {   _id: "123c",
            name: "Caldo de gallina",
            image: "caldo-de-gallina-maggi-x-270-cubos.jpg",
            price: 1000,
            description: "caldo-de-gallina-maggi",
        },
        {   _id: "123d",
            name: "Cereal froot loops",
            image: "cereal-froot-loops-kelloggs-bolsa-x-315-grs.jpg",
            price: 1000,
            description: "cereal-froot-loops-kelloggs",
        },
        {   _id: "123e",
            name: "Choco krispis",
            image: "choco-krispis-kellogs-bolsa-x-295-grs.jpg",
            price: 1000,
            description: "choco-krispis",
        },
        {   _id: "123f",
            name: "Cobertura de cacao y leche",
            image: "cobertura-cacao-y-leche-x-5000-grs.jpg",
            price: 1000,
            description: "cobertura-cacao-y-leche",
        },
        {   _id: "123g",
            name: "Cocoa corona bolsa",
            image: "cocoa-corona-bolsa-x-230-grs.jpg",
            price: 1000,
            description: "cocoa-corona-bolsa",
        },
        {   _id: "123h",
            name: "Dulce de cafe",
            image: "dulce-coffee-delight-blando-surtido-x-100-und.jpg",
            price: 1000,
            description: "dulce-coffee-delight-blando-surtido",
        },
        {   _id: "123i",
            name: "Galleta de leche muuu",
            image: "galleta-de-leche-muuu-pq-x-18-und.jpg",
            price: 1000,
            description: "galleta-de-leche-muuu",
        },
        {   _id: "123j",
            name: "Harina pan blanca",
            image: "harina-pan-blanca-x-1000-grs.jpg",
            price: 1000,
            description: "harina-pan-blanca",
        },
        {   _id: "123k",
            name: "Milo bolsa",
            image: "milo-bolsa-nestle-activ-go-x-2500-grs.jpg",
            price: 1000,
            description: "milo-bolsa-nestle",
        },
        {   _id: "123l",
            name: "Milo nuggets",
            image: "milo-nuggets-x-20-grs-.jpg",
            price: 1000,
            description: "milo-nuggets",
        }

    ]